version: "3.8"

services:
  nextjs:
    ports:
      - 5000:5000
    build:
      context: packages/landingpage
      dockerfile: Dockerfile
    volumes:
      - ./packages/landingpage:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
  mysql:
    image: mysql:8.0.22
    restart: on-failure
    networks:
      - spms-network
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: spms
      MYSQL_USER: ntt
      MYSQL_PASSWORD: mysql
    volumes:
      - ~/volumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: redis:alpine
    restart: on-failure
    networks:
      - spms-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    
networks:
  spms-network:
    driver: bridge
