version: "3.8"

services:
  mysql:
    image: mysql:8.0.22
    restart: on-failure
    networks:
      - playlist-network
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: trainning_programming
      MYSQL_USER: ntt
      MYSQL_PASSWORD: mysql
    volumes:
      - ~/volumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  playlist-network:
    driver: bridge
