name: Build

on:
  push:
    branches:
      - develop

env:
  IMAGE_TESTING: ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:testing

jobs:
  # test:
  #   name: 'Run Test'
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js version 12
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: '12'
  #   - name: npm install and test
  #     run: |
  #       npm install
  #       npm test
  
  build:
    name: 'Build docker image'
    # needs: [test]
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Get commit revision
      id: vars
      shell: bash
      run: echo ::set-output name=tag::$(echo $(git describe --long --tags --always)| sed 's/v//')

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ steps.vars.outputs.tag }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}