name: Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    name: 'Update server'
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Get commit revision
      id: vars
      shell: bash
      run: echo ::set-output name=tag::$(echo $(git describe --long --tags --always)| sed 's/v//')

    - name: SSH and deploy in server
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        KEY: ${{ secrets.SSH_KEY }}
        PORT: ${{ secrets.SSH_PORT }}
        script: |
          cd /opt/nestjs-app
          echo IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest > .env
          docker-compose up -d
